Interfaz/Controllers/CategoriasController.cs
using Dominio.Modelos;
using System;
using System.Web.Mvc;

namespace Interfaz.Controllers
{
    public class CategoriasController : Controller
    {

        Dominio.FormulariosAdministracion.Categorias _Categorias = new Dominio.FormulariosAdministracion.Categorias();

        public ActionResult Index()
        {
            if (Session["Perfil"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View(_Categorias.Consultar());
        }

        public ActionResult Create()
        {
            if (Session["Perfil"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

        [HttpPost]
        public ActionResult Create(ModeloCategoria Modelo)
        {
            _Categorias.Insertar(Modelo);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int RowId)
        {
            if (Session["Perfil"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View(_Categorias.EnviarModelo(RowId));
        }

        [HttpPost]
        public ActionResult Edit(ModeloCategoria Modelo)
        {
            _Categorias.Actualizar(Modelo);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(string RowId)
        {
            _Categorias.Eliminar(Convert.ToInt32(RowId));
            return Json("La categoria ha sido eliminada.", JsonRequestBehavior.AllowGet);
        }
    }
}

Interfaz/Views/Categorias/Create.cshtml
@model Dominio.Modelos.ModeloCategoria

@using System.Data
@using Newtonsoft.Json;

@{
    DataSet DatosImportantes = JsonConvert.DeserializeObject<DataSet>(Session["DatosImportantes"].ToString());
    string Fondo = DatosImportantes.Tables[0].Rows[0]["EP_ColorFondoCentral"].ToString();

    if (DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() != string.Empty)
    {
        Fondo = "background-image:url('" + DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() + "'); background-size: cover";
    }
}

@using (Html.BeginForm())
{
    <fieldset>
        <div class="main-panel">
            <div class="content">
                <div class="card">
                    <div class="card-body" style="@Fondo">
                        <div class="tab-content mt-2 mb-3" id="pills-with-icon-tabContent">
                            <div class="tab-pane fade show active" id="Crear-Usuarios" role="tabpanel" aria-labelledby="pills-home-tab-icon">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <div class="card">
                                            <div class="card-header">
                                                <div class="card-title">Adicionar Categorias</div>
                                            </div>
                                            <div class="card-body">

                                                <div class="row">

                                                    <div class="col-md-3">
                                                        <label for="CrearDocumento">Codigo Genero</label>
                                                        @Html.EditorFor(model => model.CodigoGeneroERP, new { htmlAttributes = new { @class = "form-control", required = "required", @PlaceHolder = "Ingresar Codigo Genero" }, })
                                                    </div>
                                                    <div class="col-md-3">
                                                        <label for="CrearDocumento">Codigo Categoria</label>
                                                        @Html.EditorFor(model => model.CodigoCategoriaERP, new { htmlAttributes = new { @class = "form-control", required = "required", @PlaceHolder = "Ingresar Codigo Categoria" }, })
                                                    </div>
                                                    <div class="col-md-3">
                                                        <label for="CrearUsuario">Descripción ERP</label>
                                                        @Html.EditorFor(model => model.DescripcionERP, new { htmlAttributes = new { @class = "form-control", @PlaceHolder = "Ingresar Descripción ERP" }, })
                                                    </div>
                                                    <div class="col-md-3">
                                                        <label for="CrearDocumento">Pilatos</label>
                                                        @Html.EditorFor(model => model.Pilatos, new { htmlAttributes = new { @class = "form-control", @PlaceHolder = "Ingresar Pilatos" }, })
                                                    </div>

                                                </div>
                                                <br />

                                                <div class="row">

                                                    <div class="col-md-3">
                                                        <label for="CrearUsuario">Diesel</label>
                                                        @Html.EditorFor(model => model.Diesel, new { htmlAttributes = new { @class = "form-control", @PlaceHolder = "Ingresar Diesel" }, })
                                                    </div>
                                                    <div class="col-md-3">
                                                        <label for="CrearDocumento">Replay</label>
                                                        @Html.EditorFor(model => model.Replay, new { htmlAttributes = new { @class = "form-control", @PlaceHolder = "Ingresar Replay" }, })
                                                    </div>
                                                    <div class="col-md-3">
                                                        <label for="CrearUsuario">SuperDry</label>
                                                        @Html.EditorFor(model => model.SuperDry, new { htmlAttributes = new { @class = "form-control", @PlaceHolder = "Ingresar SuperDry" }, })
                                                    </div>
                                                    <div class="col-md-3">
                                                        <label for="CrearDocumento">Kipling</label>
                                                        @Html.EditorFor(model => model.Kipling, new { htmlAttributes = new { @class = "form-control", @PlaceHolder = "Ingresar Kipling" }, })
                                                    </div>

                                                </div>

                                                <br />

                                                <div class="row">

                                                    <div class="col-md-3">
                                                        <label for="CrearUsuario">Girbaud</label>
                                                        @Html.EditorFor(model => model.Girbaud, new { htmlAttributes = new { @class = "form-control", @PlaceHolder = "Ingresar Girbaud" }, })
                                                    </div>

                                                </div>
                                                <br />
                                                <div class="card-action">
                                                    <input id="BtnRegistrarUsuario" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonInsertar"].ToString(); @DatosImportantes.Tables[0].Rows[0]["EP_ColorTextoBotones"].ToString()" type="submit" class="btn" value="Crear" />
                                                    <input type="button" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonRegresar"].ToString(); @DatosImportantes.Tables[0].Rows[0]["EP_ColorTextoBotones"].ToString()" class="btn" value="Regresar" onclick="location.href='@Url.Action("Index", "Categorias")'" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <footer class="footer">
                    <div class="container-fluid">
                        <div class="copyright ml-auto">
                            2019, Hecho <i class="fa fa-helicopter"></i> Por <a href="http://generictransfer.com/">Interfaces Y Soluciones</a>
                        </div>
                    </div>
                </footer>
            </div>
        </div>

        <script src="~/Content/assets/js/core/jquery.3.2.1.min.js"></script>
        <script src="~/Content/assets/js/core/popper.min.js"></script>
        <script src="~/Content/assets/js/core/bootstrap.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
        <script src="~/Content/assets/js/plugin/chart.js/chart.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>
        <script src="~/Content/assets/js/plugin/chart-circle/circles.min.js"></script>
        <script src="~/Content/assets/js/plugin/datatables/datatables.min.js"></script>
        <script src="~/Content/assets/js/plugin/jqvmap/jquery.vmap.min.js"></script>
        <script src="~/Content/assets/js/plugin/jqvmap/maps/jquery.vmap.world.js"></script>
        <script src="~/Content/assets/js/plugin/sweetalert/sweetalert.min.js"></script>
        <script src="~/Content/assets/js/atlantis.min.js"></script>
        <script src="~/Content/assets/js/setting-demo.js"></script>
        <script src="~/Content/assets/js/demo.js"></script>
    </fieldset>

    <script src="~/Content/assets/js/plugin/webfont/webfont.min.js"></script>
    <script>
        WebFont.load({
            google: { "families": ["Lato:300,400,700,900"] },
            custom: { "families": ["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['../../assets/css/fonts.min.css'] },
            active: function () {
                sessionStorage.fonts = true;
            }
        });
    </script>

}

Interfaz/Views/Categorias/Edit.cshtml
@model Dominio.Modelos.ModeloCategoria

@using System.Data
@using Newtonsoft.Json;

@{
    DataSet DatosImportantes = JsonConvert.DeserializeObject<DataSet>(Session["DatosImportantes"].ToString());
    string Fondo = DatosImportantes.Tables[0].Rows[0]["EP_ColorFondoCentral"].ToString();

    if (DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() != string.Empty)
    {
        Fondo = "background-image:url('" + DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() + "'); background-size: cover";
    }
}

@using (Html.BeginForm())
{
    <fieldset>
        <div class="main-panel">
            <div class="content">
                <div class="card">
                    <div class="card-body" style="@Fondo">
                        <div class="tab-content mt-2 mb-3" id="pills-with-icon-tabContent">
                            <div class="tab-pane fade show active" id="Crear-Usuarios" role="tabpanel" aria-labelledby="pills-home-tab-icon">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <div class="card">
                                            <div class="card-header">
                                                <div class="card-title">Actualizar Categorias</div>
                                            </div>
                                            <div class="card-body">
                                                @Html.HiddenFor(x => x.RowId)

                                                <div class="row">

                                                    <div class="col-md-3">
                                                        <label for="CrearDocumento">Codigo Genero</label>
                                                        @Html.EditorFor(model => model.CodigoGeneroERP, new { htmlAttributes = new { @class = "form-control", required = "required", @PlaceHolder = "Ingresar Codigo Genero" }, })
                                                    </div>
                                                    <div class="col-md-3">
                                                        <label for="CrearDocumento">Codigo Categoria</label>
                                                        @Html.EditorFor(model => model.CodigoCategoriaERP, new { htmlAttributes = new { @class = "form-control", required = "required", @PlaceHolder = "Ingresar Codigo Categoria" }, })
                                                    </div>
                                                    <div class="col-md-3">
                                                        <label for="CrearUsuario">Descripción ERP</label>
                                                        @Html.EditorFor(model => model.DescripcionERP, new { htmlAttributes = new { @class = "form-control", @PlaceHolder = "Ingresar Descripción ERP" }, })
                                                    </div>
                                                    <div class="col-md-3">
                                                        <label for="CrearDocumento">Pilatos</label>
                                                        @Html.EditorFor(model => model.Pilatos, new { htmlAttributes = new { @class = "form-control", @PlaceHolder = "Ingresar Pilatos" }, })
                                                    </div>

                                                </div>
                                                <br />

                                                <div class="row">
                                                    <div class="col-md-3">
                                                        <label for="CrearUsuario">Diesel</label>
                                                        @Html.EditorFor(model => model.Diesel, new { htmlAttributes = new { @class = "form-control", @PlaceHolder = "Ingresar Diesel" }, })
                                                    </div>
                                                    <div class="col-md-3">
                                                        <label for="CrearDocumento">Replay</label>
                                                        @Html.EditorFor(model => model.Replay, new { htmlAttributes = new { @class = "form-control", @PlaceHolder = "Ingresar Replay" }, })
                                                    </div>
                                                    <div class="col-md-3">
                                                        <label for="CrearUsuario">SuperDry</label>
                                                        @Html.EditorFor(model => model.SuperDry, new { htmlAttributes = new { @class = "form-control", @PlaceHolder = "Ingresar SuperDry" }, })
                                                    </div>
                                                    <div class="col-md-3">
                                                        <label for="CrearDocumento">Kipling</label>
                                                        @Html.EditorFor(model => model.Kipling, new { htmlAttributes = new { @class = "form-control", @PlaceHolder = "Ingresar Kipling" }, })
                                                    </div>

                                                </div>

                                                <br />

                                                <div class="row">

                                                    <div class="col-md-3">
                                                        <label for="CrearUsuario">Girbaud</label>
                                                        @Html.EditorFor(model => model.Girbaud, new { htmlAttributes = new { @class = "form-control", @PlaceHolder = "Ingresar Girbaud" }, })
                                                    </div>

                                                </div>
                                                <br />
                                            </div>
                                            <div class="card-action">
                                                <input id="BtnRegistrarUsuario" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonActualizar"].ToString(); @DatosImportantes.Tables[0].Rows[0]["EP_ColorTextoBotones"].ToString()" type="submit" class="btn" value="Actualizar" />
                                                <input type="button" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonRegresar"].ToString(); @DatosImportantes.Tables[0].Rows[0]["EP_ColorTextoBotones"].ToString()" class="btn" value="Regresar" onclick="location.href='@Url.Action("Index", "Categorias")'" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <footer class="footer">
                <div class="container-fluid">
                    <div class="copyright ml-auto">
                        2019, Hecho <i class="fa fa-helicopter"></i> Por <a href="http://generictransfer.com/">Interfaces Y Soluciones</a>
                    </div>
                </div>
            </footer>
        </div>

        <script src="~/Content/assets/js/core/jquery.3.2.1.min.js"></script>
        <script src="~/Content/assets/js/core/popper.min.js"></script>
        <script src="~/Content/assets/js/core/bootstrap.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
        <script src="~/Content/assets/js/plugin/chart.js/chart.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>
        <script src="~/Content/assets/js/plugin/chart-circle/circles.min.js"></script>
        <script src="~/Content/assets/js/plugin/datatables/datatables.min.js"></script>
        <script src="~/Content/assets/js/plugin/jqvmap/jquery.vmap.min.js"></script>
        <script src="~/Content/assets/js/plugin/jqvmap/maps/jquery.vmap.world.js"></script>
        <script src="~/Content/assets/js/plugin/sweetalert/sweetalert.min.js"></script>
        <script src="~/Content/assets/js/atlantis.min.js"></script>
        <script src="~/Content/assets/js/setting-demo.js"></script>
        <script src="~/Content/assets/js/demo.js"></script>
    </fieldset>

    <script src="~/Content/assets/js/plugin/webfont/webfont.min.js"></script>
    <script>
        WebFont.load({
            google: { "families": ["Lato:300,400,700,900"] },
            custom: { "families": ["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['../../assets/css/fonts.min.css'] },
            active: function () {
                sessionStorage.fonts = true;
            }
        });
    </script>

}

Interfaz/Views/Categorias/Index.cshtml
@using System.Data
@using Newtonsoft.Json;

@model DataSet

@{
    DataSet DatosImportantes = JsonConvert.DeserializeObject<DataSet>(Session["DatosImportantes"].ToString());
    string Fondo = DatosImportantes.Tables[0].Rows[0]["EP_ColorFondoCentral"].ToString();

    if (DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() != string.Empty)
    {
        Fondo = "background-image:url('" + DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() + "'); background-size: cover";
    }

    var Contador = 0;
}

<div class="main-panel">
    <div class="content">
        <div class="card">
            <div class="card-body" style="@Fondo">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header row">
                                <div class="col-md-10"><h4 class="card-title">Modulo Categorias</h4></div>
                                <div class="col-md-2"><input id="Button1" type="submit" value="Crear" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonInsertar"].ToString()" class="form-control btn btn-primary" onclick="location.href='@Url.Action("Create", "Categorias")'" /></div>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table id="basic-datatables" class="display table table-striped table-hover">
                                        <thead>
                                            <tr>
                                                @foreach (DataColumn item in Model.Tables[0].Columns)
                                                {
                                                    if (Contador > 0)
                                                    {
                                                        <th>@item.ColumnName.ToString()</th>
                                                    }
                                                    Contador++;
                                                }
                                                <th>Acciones</th>
                                            </tr>
                                        </thead>

                                        <tfoot>
                                            @if (Model.Tables[0].Rows.Count >= 5)
                                            {
                                                Contador = 0;
                                                <tr>
                                                    @foreach (DataColumn item in Model.Tables[0].Columns)
                                                    {
                                                        if (Contador > 0)
                                                        {
                                                            <th>@item.ColumnName.ToString()</th>
                                                        }
                                                        Contador++;
                                                    }
                                                    <th>Acciones</th>
                                                </tr>
                                            }
                                        </tfoot>
                                        <tbody>
                                            @foreach (DataRow row in Model.Tables[0].Rows)
                                            {
                                                Contador = 0;
                                                <tr>
                                                    @foreach (DataColumn item in Model.Tables[0].Columns)
                                                    {
                                                        if (Contador > 0)
                                                        {
                                                            <td>@row[item.ColumnName.ToString()]</td>
                                                        }
                                                        Contador++;
                                                    }
                                                    <td>
                                                        <input type="button" value="Editar" class="btn" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonActualizar"].ToString(); @DatosImportantes.Tables[0].Rows[0]["EP_ColorTextoBotones"].ToString()" onclick="location.href='@Url.Action("Edit", "Categorias")?RowId=' +  @row[Model.Tables[0].Columns[0].ToString()]" />
                                                        <input type="button" value="Eliminar" class="btn" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonConsultar"].ToString(); @DatosImportantes.Tables[0].Rows[0]["EP_ColorTextoBotones"].ToString()" onclick="Eliminar(@row[Model.Tables[0].Columns[0].ToString()])" />
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer class="footer">
        <div class="container-fluid">
            <div class="copyright ml-auto">
                2019, Hecho <i class="fa fa-helicopter"></i> Por <a href="http://generictransfer.com/">Interfaces Y Soluciones</a>
            </div>
        </div>
    </footer>
</div>

<script src="~/Content/assets/js/core/jquery.3.2.1.min.js"></script>
<script src="~/Content/assets/js/core/popper.min.js"></script>
<script src="~/Content/assets/js/core/bootstrap.min.js"></script>
<script src="~/Content/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
<script src="~/Content/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
<script src="~/Content/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
<script src="~/Content/assets/js/plugin/datatables/datatables.min.js"></script>
<script src="~/Content/assets/js/atlantis.min.js"></script>

<script>
    function Eliminar(RowId) {
        swal({
            title: "Estás seguro?",
            text: "Una vez eliminado no podras recuperar la información.",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((Eliminar) => {
                if (Eliminar) {
                    $.ajax({
                        type: "POST",
                        data: {
                            RowId: RowId
                        },
                        url: "/Categorias/Delete",
                        dataType: "json",
                        success: function (response) {
                            swal(response, {
                                icon: "success",
                            }).then(function () {
                                window.location.href = "/Categorias/Index"
                            });

                        },
                        failure: function (response) {
                            alert(response.responseText);
                        },
                        error: function (response) {
                            alert(response.responseText);
                        }
                    });

                }
                else {
                    swal("Felicidades, No has eliminado esta categoria!");
                }
            });
    }

    $(document).ready(function () {
        $('#basic-datatables').DataTable({
        });

        $('#multi-filter-select').DataTable({
            "pageLength": 5,
            initComplete: function () {
                this.api().columns().every(function () {
                    var column = this;
                    var select = $('<select class="form-control"><option value=""></option></select>')
                        .appendTo($(column.footer()).empty())
                        .on('change', function () {
                            var val = $.fn.dataTable.util.escapeRegex(
                                $(this).val()
                            );

                            column
                                .search(val ? '^' + val + '$' : '', true, false)
                                .draw();
                        });

                    column.data().unique().sort().each(function (d, j) {
                        select.append('<option value="' + d + '">' + d + '</option>')
                    });
                });
            }
        });

        $('#add-row').DataTable({
            "pageLength": 5,
        });

        var action = '<td> <div class="form-button-action"> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-primary btn-lg" data-original-title="Edit Task"> <i class="fa fa-edit"></i> </button> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-danger" data-original-title="Remove"> <i class="fa fa-times"></i> </button> </div> </td>';

        $('#addRowButton').click(function () {
            $('#add-row').dataTable().fnAddData([
                $("#addName").val(),
                $("#addPosition").val(),
                $("#addOffice").val(),
                action
            ]);
            $('#addRowModal').modal('hide');

        });
    });
</script>