Interfaz/Controllers/PermisosController.cs
using System;
using System.Web.Mvc;

namespace Interfaz.Controllers
{
    public class PermisosController : Controller
    {
        Dominio.FormulariosAdministracion.Permisos _Permisos = new Dominio.FormulariosAdministracion.Permisos();

        public ActionResult Index()
        {
            if (Session["Perfil"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if ((int)Session["Perfil"] == 2)
            {
                return View(_Permisos.Consultar());
            }

            return RedirectToAction("Index", "Login");
        }

        [HttpGet]
        public ActionResult EditMenu(string Check, string RowId)
        {
            _Permisos.Actualizar(Convert.ToInt32(RowId), "Visible", Convert.ToBoolean(Check));
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditSubMenu(string Check, string RowId)
        {
            _Permisos.Actualizar(Convert.ToInt32(RowId), "VisibleSubMenu", Convert.ToBoolean(Check));
            return RedirectToAction("Index");
        }
    }
}

Interfaz/Controllers/PropiedadesController.cs
using Dominio.Modelos;
using System;
using System.Web.Mvc;

namespace Interfaz.Controllers
{
    public class PropiedadesController : Controller
    {
        Dominio.FormulariosAdministracion.Propiedades _Propiedades = new Dominio.FormulariosAdministracion.Propiedades();

        public ActionResult Index()
        {
            if (Session["Perfil"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if ((int)Session["Perfil"] == 2)
            {
                return View(_Propiedades.Consultar());
            }

            return RedirectToAction("Index", "Login");
        }

        public ActionResult Create()
        {
            if (Session["Perfil"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if ((int)Session["Perfil"] == 2)
            {
                return View("Create");
            }

            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        public ActionResult Create(ModeloPropiedad Modelo)
        {
            if (_Propiedades.Insertar(Modelo) == "EXISTE")
            {
                ViewData["Error"] = "EL NOMBRE DE LA PROPIEDAD YA EXISTE...";
                return View(Modelo);
            }

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int RowId)
        {
            if (Session["Perfil"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if ((int)Session["Perfil"] == 2)
            {
                return View(_Propiedades.EnviarModelo(RowId));
            }
            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        public ActionResult Edit(ModeloPropiedad Modelo)
        {
            _Propiedades.Actualizar(Modelo);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int RowId)
        {
            if (Session["Perfil"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if ((int)Session["Perfil"] == 2)
            {
                return View(_Propiedades.EnviarModelo(RowId));
            }
            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        public ActionResult Delete(string RowId)
        {
            _Propiedades.Eliminar(Convert.ToInt32(RowId));
            return Json("La propiedad ha sido eliminada.", JsonRequestBehavior.AllowGet);
        }
    }
}

Interfaz/Views/Permisos/Index.cshtml
@using System.Data
@using Newtonsoft.Json;
@model DataSet

@{
    DataSet DatosImportantes = JsonConvert.DeserializeObject<DataSet>(Session["DatosImportantes"].ToString());
    string Fondo = DatosImportantes.Tables[0].Rows[0]["EP_ColorFondoCentral"].ToString();

    if (DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() != string.Empty)
    {
        Fondo = "background-image:url('" + DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() + "'); background-size: cover";
    }
}

<div class="main-panel">
    <div class="content">
        <div class="card">
            <div class="card-body" style="@Fondo">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header row">
                                <div class="col-md-10"><h4 class="card-title">Modulo Permisos</h4></div>
                                @*<div class="col-md-2"><input id="Button1" type="submit" value="Crear" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonInsertar"].ToString()" class="form-control btn btn-primary" onclick="location.href='@Url.Action("Create", "Propiedades")'" /></div>*@
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table id="basic-datatables" class="display table table-striped table-hover">
                                        <thead>
                                            <tr>
                                                @foreach (DataColumn item in Model.Tables[0].Columns)
                                                {
                                                    <th>@item.ColumnName.ToString()</th>
                                                }
                                            </tr>
                                        </thead>

                                        <tfoot>
                                            @if (Model.Tables[0].Rows.Count >= 5)
                                            {
                                                <tr>
                                                    @foreach (DataColumn item in Model.Tables[0].Columns)
                                                    {
                                                        <th>@item.ColumnName.ToString()</th>
                                                    }
                                                </tr>
                                            }
                                        </tfoot>
                                        <tbody>
                                            @foreach (DataRow row in Model.Tables[0].Rows)
                                            {
                                                <tr>
                                                    <td>@row["Id"]</td>
                                                    <td>@row["Perfil"]</td>
                                                    <td>@row["Menu"]</td>
                                                    @if (Convert.ToBoolean(@row["VisibleMenu"]))
                                                    {
                                                        <td><input id="CheckMenu" class="CheckMenu" type="checkbox" checked /></td>
                                                    }
                                                    else
                                                    {
                                                        <td><input id="CheckMenu" class="CheckMenu" type="checkbox" /></td>

                                                    }
                                                    <td>@row["SubMenu"]</td>
                                                    @if (Convert.ToBoolean(@row["VisibleSubMenu"]))
                                                    {
                                                        <td><input id="CheckSubMenu" class="CheckSubMenu" type="checkbox" checked /></td>
                                                    }
                                                    else
                                                    {
                                                        <td><input id="CheckSubMenu" class="CheckSubMenu" type="checkbox" /></td>

                                                    }
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer class="footer">
        <div class="container-fluid">
            <div class="copyright ml-auto">
                2019, Hecho <i class="fa fa-helicopter"></i> Por <a href="http://generictransfer.com/">Interfaces Y Soluciones</a>
            </div>
        </div>
    </footer>
</div>

<script src="~/Content/assets/js/core/jquery.3.2.1.min.js"></script>
<script src="~/Content/assets/js/core/popper.min.js"></script>
<script src="~/Content/assets/js/core/bootstrap.min.js"></script>
<script src="~/Content/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
<script src="~/Content/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
<script src="~/Content/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
<script src="~/Content/assets/js/plugin/chart.js/chart.min.js"></script>
<script src="~/Content/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>
<script src="~/Content/assets/js/plugin/chart-circle/circles.min.js"></script>
<script src="~/Content/assets/js/plugin/datatables/datatables.min.js"></script>
<script src="~/Content/assets/js/plugin/jqvmap/jquery.vmap.min.js"></script>
<script src="~/Content/assets/js/plugin/jqvmap/maps/jquery.vmap.world.js"></script>
<script src="~/Content/assets/js/plugin/sweetalert/sweetalert.min.js"></script>
<script src="~/Content/assets/js/atlantis.min.js"></script>
<script src="~/Content/assets/js/setting-demo.js"></script>
<script src="~/Content/assets/js/demo.js"></script>


<script>
    var Check = "";
    $(".CheckMenu").click(function (obj) {
        var RowId = $(this).parents("tr").find("td").eq(0).html();
        Check = obj.target.checked;

        $(document).ready(function () {
            $.ajax({
                url: '@Url.Action("EditMenu", "Permisos")',
                type: 'GET',
                dataType: 'json',
                cache: false,
                data: {
                    'Check': Check,
                    'RowId': RowId
                },
                success: function (results) {
                    return true;
                },
                error: function () {
                    return false;
                }
            });
        });
    })

    $(".CheckSubMenu").click(function (obj) {
        var RowId = $(this).parents("tr").find("td").eq(0).html();
        Check = obj.target.checked;

        $(document).ready(function () {
            $.ajax({
                url: '@Url.Action("EditSubMenu", "Permisos")',
                type: 'GET',
                dataType: 'json',
                cache: false,
                data: {
                    'Check': Check,
                    'RowId': RowId
                },
                success: function (results) {
                    return true;
                },
                error: function () {
                    return false;
                }
            });
        });
    })

    $(document).ready(function () {
        $('#basic-datatables').DataTable({
        });

        $('#multi-filter-select').DataTable({
            "pageLength": 5,
            initComplete: function () {
                this.api().columns().every(function () {
                    var column = this;
                    var select = $('<select class="form-control"><option value=""></option></select>')
                        .appendTo($(column.footer()).empty())
                        .on('change', function () {
                            var val = $.fn.dataTable.util.escapeRegex(
                                $(this).val()
                            );

                            column
                                .search(val ? '^' + val + '$' : '', true, false)
                                .draw();
                        });

                    column.data().unique().sort().each(function (d, j) {
                        select.append('<option value="' + d + '">' + d + '</option>')
                    });
                });
            }
        });

        $('#add-row').DataTable({
            "pageLength": 5,
        });

        var action = '<td> <div class="form-button-action"> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-primary btn-lg" data-original-title="Edit Task"> <i class="fa fa-edit"></i> </button> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-danger" data-original-title="Remove"> <i class="fa fa-times"></i> </button> </div> </td>';

        $('#addRowButton').click(function () {
            $('#add-row').dataTable().fnAddData([
                $("#addName").val(),
                $("#addPosition").val(),
                $("#addOffice").val(),
                action
            ]);
            $('#addRowModal').modal('hide');

        });
    });
</script>