Interfaz/Controllers/UsuariosController.cs
using Dominio.Modelos;
using System;
using System.Web.Mvc;

namespace Interfaz.Controllers
{
    public class UsuariosController : Controller
    {
        Dominio.FormulariosAdministracion.Usuarios _Usuarios = new Dominio.FormulariosAdministracion.Usuarios();
        Dominio.Recursos.Combos _Combos = new Dominio.Recursos.Combos();

        public ActionResult Index()
        {
            if (Session["Perfil"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if ((int)Session["Perfil"] == 2)
            {
                return View(_Usuarios.Consultar());
            }

            return RedirectToAction("Index", "Login");
        }

        public ActionResult Create()
        {
            if (Session["Perfil"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if ((int)Session["Perfil"] == 2)
            {
                ViewBag.ListadoPerfiles = _Combos.Obtener("Sp_ListadoPerfiles");
                return View("Create");
            }

            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        public ActionResult Create(ModeloUsuario Modelo)
        {
            if (_Usuarios.ValidarUsuario(Modelo.Usuario) == "EXISTE")
            {
                ViewData["Error"] = "EL USUARIO YA EXISTE...";
                ViewBag.ListadoPerfiles = _Combos.Obtener("Sp_ListadoPerfiles", Modelo.RowId.ToString());
                return View(Modelo);
            }

            _Usuarios.Insertar(Modelo);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int RowId)
        {
            if (Session["Perfil"] == null)
            {
                return RedirectToAction("Index", "Login");
            }

            if ((int)Session["Perfil"] == 2)
            {
                RecuperarCombo(RowId);
                return View(_Usuarios.EnviarModelo(RowId));
            }
            return RedirectToAction("Index", "Login");
        }

        [HttpPost]
        public ActionResult Edit(ModeloUsuario Modelo)
        {
            _Usuarios.Actualizar(Modelo);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(string RowId)
        {
            _Usuarios.Eliminar(Convert.ToInt32(RowId));
            return Json("El usuario ha sido eliminado.", JsonRequestBehavior.AllowGet);
        }

        private void RecuperarCombo(int RowId)
        {
            ViewBag.ListadoPerfiles = _Combos.Obtener("Sp_ListadoPerfiles", _Usuarios.EnviarModelo(RowId).IdPerfil.ToString());
        }
    }
}

Interfaz/Views/Usuarios/Create.cshtml
@model Dominio.Modelos.ModeloUsuario

@using System.Data
@using Newtonsoft.Json;

@{
    DataSet DatosImportantes = JsonConvert.DeserializeObject<DataSet>(Session["DatosImportantes"].ToString());
    string Fondo = DatosImportantes.Tables[0].Rows[0]["EP_ColorFondoCentral"].ToString();

    if (DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() != string.Empty)
    {
        Fondo = "background-image:url('" + DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() + "'); background-size: cover";
    }
}

@using (Html.BeginForm())
{
    <fieldset>
        <div class="main-panel">
            <div class="content">
                <div class="card">
                    <div class="card-body" style="@Fondo">
                        <div class="tab-content mt-2 mb-3" id="pills-with-icon-tabContent">
                            <div class="tab-pane fade show active" id="Crear-Usuarios" role="tabpanel" aria-labelledby="pills-home-tab-icon">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <div class="card">
                                            <div class="card-header">
                                                <div class="card-title">Adicionar Usuarios</div>
                                                <a style="color:red">@ViewData["Error"]</a>
                                            </div>
                                            <div class="card-body">
                                                <div class="row">
                                                    <div class="col-md-4">
                                                        <label for="CrearUsuario">Usuario</label>
                                                        @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control", required = "required", @PlaceHolder = "Ingresar Usuario" }, })
                                                    </div>
                                                    <div class="col-md-4">
                                                        <label for="CrearClave">Clave</label>
                                                        @Html.EditorFor(model => model.Clave, new { htmlAttributes = new { @class = "form-control", required = "required", @PlaceHolder = "Ingresar Clave" }, })
                                                    </div>
                                                    <div class="col-md-4">
                                                        <label for="perfil">Perfil</label>

                                                        <select id="idPerfil" name="idPerfil" class="form-control" required="required">
                                                            @foreach (var listItem in (List<SelectListItem>)ViewBag.ListadoPerfiles)
                                                            {
                                                                <option value="@listItem.Value" @(listItem.Selected ? "selected" : "")>
                                                                    @listItem.Text
                                                                </option>
                                                            }
                                                        </select>

                                                    </div>
                                                </div>
                                                <br />
                                                <div class="row">
                                                    <div class="col-md-4">
                                                        <label for="CrearDocumento">Documento</label>
                                                        @Html.EditorFor(model => model.Documento, new { htmlAttributes = new { @class = "form-control", required = "required", @PlaceHolder = "Ingresar Documento" }, })
                                                    </div>
                                                    <div class="col-md-4">
                                                        <label for="CrearNombreCompleto">Nombre Completo</label>
                                                        @Html.EditorFor(model => model.NombreCompleto, new { htmlAttributes = new { @class = "form-control", required = "required", @PlaceHolder = "Ingresar Nombre Completo" }, })
                                                    </div>
                                                    <div class="col-md-4">
                                                        <label for="CrearCorreo">Correo</label>
                                                        @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control", @PlaceHolder = "Ingresar Correo" }, })
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="card-action">
                                                <input id="BtnRegistrarUsuario" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonInsertar"].ToString(); @DatosImportantes.Tables[0].Rows[0]["EP_ColorTextoBotones"].ToString()" type="submit" class="btn" value="Crear" />
                                                <input type="button" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonRegresar"].ToString(); @DatosImportantes.Tables[0].Rows[0]["EP_ColorTextoBotones"].ToString()" class="btn" value="Regresar" onclick="location.href='@Url.Action("Index", "Usuarios")'" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <footer class="footer">
                <div class="container-fluid">
                    <div class="copyright ml-auto">
                        2019, Hecho <i class="fa fa-helicopter"></i> Por <a href="http://generictransfer.com/">Interfaces Y Soluciones</a>
                    </div>
                </div>
            </footer>
        </div>

        <script src="~/Content/assets/js/core/jquery.3.2.1.min.js"></script>
        <script src="~/Content/assets/js/core/popper.min.js"></script>
        <script src="~/Content/assets/js/core/bootstrap.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
        <script src="~/Content/assets/js/plugin/chart.js/chart.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>
        <script src="~/Content/assets/js/plugin/chart-circle/circles.min.js"></script>
        <script src="~/Content/assets/js/plugin/datatables/datatables.min.js"></script>
        <script src="~/Content/assets/js/plugin/jqvmap/jquery.vmap.min.js"></script>
        <script src="~/Content/assets/js/plugin/jqvmap/maps/jquery.vmap.world.js"></script>
        <script src="~/Content/assets/js/plugin/sweetalert/sweetalert.min.js"></script>
        <script src="~/Content/assets/js/atlantis.min.js"></script>
        <script src="~/Content/assets/js/setting-demo.js"></script>
        <script src="~/Content/assets/js/demo.js"></script>
    </fieldset>

    <script src="~/Content/assets/js/plugin/webfont/webfont.min.js"></script>
    <script>
        WebFont.load({
            google: { "families": ["Lato:300,400,700,900"] },
            custom: { "families": ["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['../../assets/css/fonts.min.css'] },
            active: function () {
                sessionStorage.fonts = true;
            }
        });
    </script>

}

Interfaz/Views/Usuarios/Edit.cshtml
@model Dominio.Modelos.ModeloUsuario

@using System.Data
@using Newtonsoft.Json;

@{
    DataSet DatosImportantes = JsonConvert.DeserializeObject<DataSet>(Session["DatosImportantes"].ToString());
    string Fondo = DatosImportantes.Tables[0].Rows[0]["EP_ColorFondoCentral"].ToString();

    if (DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() != string.Empty)
    {
        Fondo = "background-image:url('" + DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() + "'); background-size: cover";
    }
}

@using (Html.BeginForm())
{
    <fieldset>
        <div class="main-panel">
            <div class="content">
                <div class="card">
                    <div class="card-body" style="@Fondo">
                        <div class="tab-content mt-2 mb-3" id="pills-with-icon-tabContent">
                            <div class="tab-pane fade show active" id="Crear-Usuarios" role="tabpanel" aria-labelledby="pills-home-tab-icon">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <div class="card">
                                            <div class="card-header">
                                                <div class="card-title">Actualizar Usuarios</div>
                                            </div>
                                            <div class="card-body">
                                                @Html.HiddenFor(x => x.RowId)
                                                <div class="row">
                                                    <div class="col-md-4">
                                                        <label for="CrearUsuario">Usuario</label>
                                                        @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control", required = "required", @PlaceHolder = "Ingresar Usuario" }, })
                                                    </div>
                                                    <div class="col-md-4">
                                                        <label for="CrearClave">Clave</label>
                                                        @Html.EditorFor(model => model.Clave, new { htmlAttributes = new { @class = "form-control", required = "required", @PlaceHolder = "Ingresar Clave" }, })
                                                    </div>
                                                    <div class="col-md-4">
                                                        <label for="perfil">Perfil</label>

                                                        <select id="idPerfil" name="idPerfil" class="form-control">
                                                            @foreach (var listItem in (List<SelectListItem>)ViewBag.ListadoPerfiles)
                                                            {
                                                                <option value="@listItem.Value" @(listItem.Selected ? "selected" : "")>
                                                                    @listItem.Text
                                                                </option>
                                                            }
                                                        </select>

                                                    </div>
                                                </div>
                                                <br />
                                                <div class="row">
                                                    <div class="col-md-4">
                                                        <label for="CrearDocumento">Documento</label>
                                                        @Html.EditorFor(model => model.Documento, new { htmlAttributes = new { @class = "form-control", required = "required", @PlaceHolder = "Ingresar Documento" }, })
                                                    </div>
                                                    <div class="col-md-4">
                                                        <label for="CrearNombreCompleto">Nombre Completo</label>
                                                        @Html.EditorFor(model => model.NombreCompleto, new { htmlAttributes = new { @class = "form-control", required = "required", @PlaceHolder = "Ingresar Nombre Completo" }, })
                                                    </div>
                                                    <div class="col-md-4">
                                                        <label for="CrearCorreo">Correo</label>
                                                        @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control", @PlaceHolder = "Ingresar Correo" }, })
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="card-action">
                                                <input id="BtnRegistrarUsuario" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonActualizar"].ToString(); @DatosImportantes.Tables[0].Rows[0]["EP_ColorTextoBotones"].ToString()" type="submit" class="btn" value="Actualizar" />
                                                <input type="button" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonRegresar"].ToString(); @DatosImportantes.Tables[0].Rows[0]["EP_ColorTextoBotones"].ToString()" class="btn" value="Regresar" onclick="location.href='@Url.Action("Index", "Usuarios")'" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <footer class="footer">
                <div class="container-fluid">
                    <div class="copyright ml-auto">
                        2019, Hecho <i class="fa fa-helicopter"></i> Por <a href="http://generictransfer.com/">Interfaces Y Soluciones</a>
                    </div>
                </div>
            </footer>
        </div>

        <script src="~/Content/assets/js/core/jquery.3.2.1.min.js"></script>
        <script src="~/Content/assets/js/core/popper.min.js"></script>
        <script src="~/Content/assets/js/core/bootstrap.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
        <script src="~/Content/assets/js/plugin/chart.js/chart.min.js"></script>
        <script src="~/Content/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>
        <script src="~/Content/assets/js/plugin/chart-circle/circles.min.js"></script>
        <script src="~/Content/assets/js/plugin/datatables/datatables.min.js"></script>
        <script src="~/Content/assets/js/plugin/jqvmap/jquery.vmap.min.js"></script>
        <script src="~/Content/assets/js/plugin/jqvmap/maps/jquery.vmap.world.js"></script>
        <script src="~/Content/assets/js/plugin/sweetalert/sweetalert.min.js"></script>
        <script src="~/Content/assets/js/atlantis.min.js"></script>
        <script src="~/Content/assets/js/setting-demo.js"></script>
        <script src="~/Content/assets/js/demo.js"></script>
    </fieldset>

    <script src="~/Content/assets/js/plugin/webfont/webfont.min.js"></script>
    <script>
        WebFont.load({
            google: { "families": ["Lato:300,400,700,900"] },
            custom: { "families": ["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['../../assets/css/fonts.min.css'] },
            active: function () {
                sessionStorage.fonts = true;
            }
        });
    </script>

}

Interfaz/Views/Usuarios/Index.cshtml
@using System.Data
@using Newtonsoft.Json;
@model DataSet

@{
    DataSet DatosImportantes = JsonConvert.DeserializeObject<DataSet>(Session["DatosImportantes"].ToString());
    string Fondo = DatosImportantes.Tables[0].Rows[0]["EP_ColorFondoCentral"].ToString();

    if (DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() != string.Empty)
    {
        Fondo = "background-image:url('" + DatosImportantes.Tables[0].Rows[0]["EP_UrlFondo"].ToString() + "'); background-size: cover";
    }

    var Contador = 0;
}

<div class="main-panel">
    <div class="content">
        <div class="card">
            <div class="card-body" style="@Fondo">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header row">
                                <div class="col-md-10"><h4 class="card-title">Modulo Usuarios</h4></div>
                                <div class="col-md-2"><input id="Button1" type="submit" value="Crear" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonInsertar"].ToString(); @DatosImportantes.Tables[0].Rows[0]["EP_ColorTextoBotones"].ToString()" class="form-control btn" onclick="location.href='@Url.Action("Create", "Usuarios")'" /></div>
                            </div>
                            <div class="card-body">
                                <div class="table-responsive">
                                    <table id="basic-datatables" class="display table table-striped table-hover">
                                        <thead>
                                            <tr>
                                                @foreach (DataColumn item in Model.Tables[0].Columns)
                                                {
                                                    if (Contador > 0)
                                                    {
                                                        <th>@item.ColumnName.ToString()</th>
                                                    }
                                                    Contador++;
                                                }
                                                <th style="text-align:center">Acciones</th>
                                            </tr>
                                        </thead>

                                        <tfoot>
                                            @if (Model.Tables[0].Rows.Count >= 5)
                                            {
                                                Contador = 0;
                                                <tr>
                                                    @foreach (DataColumn item in Model.Tables[0].Columns)
                                                    {
                                                        if (Contador > 0)
                                                        {
                                                            <th>@item.ColumnName.ToString()</th>
                                                        }
                                                        Contador++;
                                                    }
                                                    <th style="text-align:center">Acciones</th>
                                                </tr>
                                            }
                                        </tfoot>
                                        <tbody>
                                            @foreach (DataRow row in Model.Tables[0].Rows)
                                            {
                                                Contador = 0;
                                                <tr>
                                                    @foreach (DataColumn item in Model.Tables[0].Columns)
                                                    {
                                                        if (Contador > 0)
                                                        {
                                                            <td>@row[item.ColumnName.ToString()]</td>
                                                        }
                                                        Contador++;
                                                    }
                                                    <td style="text-align:center">
                                                        <input type="button" value="Editar" class="btn" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonActualizar"].ToString(); @DatosImportantes.Tables[0].Rows[0]["EP_ColorTextoBotones"].ToString()" onclick="location.href='@Url.Action("Edit", "Usuarios")?RowId=' +  @row[Model.Tables[0].Columns[0].ToString()]" />
                                                        <input type="button" value="Eliminar" class="btn" style="@DatosImportantes.Tables[0].Rows[0]["EP_ColorBotonConsultar"].ToString(); @DatosImportantes.Tables[0].Rows[0]["EP_ColorTextoBotones"].ToString()" onclick="Eliminar(@row[Model.Tables[0].Columns[0].ToString()])" />
                                                    </td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <footer class="footer">
        <div class="container-fluid">
            <div class="copyright ml-auto">
                2019, Hecho <i class="fa fa-helicopter"></i> Por <a href="http://generictransfer.com/">Interfaces Y Soluciones</a>
            </div>
        </div>
    </footer>
</div>

<script src="~/Content/assets/js/core/jquery.3.2.1.min.js"></script>
<script src="~/Content/assets/js/core/popper.min.js"></script>
<script src="~/Content/assets/js/core/bootstrap.min.js"></script>
<script src="~/Content/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
<script src="~/Content/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
<script src="~/Content/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>
<script src="~/Content/assets/js/plugin/datatables/datatables.min.js"></script>
<script src="~/Content/assets/js/atlantis.min.js"></script>

<script>
    function Eliminar(RowId) {
        swal({
            title: "Estás seguro?",
            text: "Una vez eliminado no podras recuperar la información.",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((Eliminar) => {
                if (Eliminar) {
                    $.ajax({
                        type: "POST",
                        data: {
                            RowId: RowId
                        },
                        url: "/Usuarios/Delete",
                        dataType: "json",
                        success: function (response) {
                            swal(response, {
                                icon: "success",
                            }).then(function () {
                                window.location.href = "/Usuarios/Index"
                            });

                        },
                        failure: function (response) {
                            alert(response.responseText);
                        },
                        error: function (response) {
                            alert(response.responseText);
                        }
                    });

                }
                else {
                    swal("Felicidades, No has eliminado este usuario!");
                }
            });
    }

    $(document).ready(function () {
        $('#basic-datatables').DataTable({
        });

        $('#multi-filter-select').DataTable({
            "pageLength": 5,
            initComplete: function () {
                this.api().columns().every(function () {
                    var column = this;
                    var select = $('<select class="form-control"><option value=""></option></select>')
                        .appendTo($(column.footer()).empty())
                        .on('change', function () {
                            var val = $.fn.dataTable.util.escapeRegex(
                                $(this).val()
                            );

                            column
                                .search(val ? '^' + val + '$' : '', true, false)
                                .draw();
                        });

                    column.data().unique().sort().each(function (d, j) {
                        select.append('<option value="' + d + '">' + d + '</option>')
                    });
                });
            }
        });

        // Add Row
        $('#add-row').DataTable({
            "pageLength": 5,
        });

        var action = '<td> <div class="form-button-action"> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-primary btn-lg" data-original-title="Edit Task"> <i class="fa fa-edit"></i> </button> <button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-danger" data-original-title="Remove"> <i class="fa fa-times"></i> </button> </div> </td>';

        $('#addRowButton').click(function () {
            $('#add-row').dataTable().fnAddData([
                $("#addName").val(),
                $("#addPosition").val(),
                $("#addOffice").val(),
                action
            ]);
            $('#addRowModal').modal('hide');

        });
    });
</script>